---

- name: Create /opt/bin
  ansible.builtin.file:
    path: /opt/bin
    state: directory
    owner: root
    group: root

- name: Create /var/lib/libvirt/terraform/base_images/ to store base cloud images
  ansible.builtin.file:
    path: /var/lib/libvirt/terraform/base_images/
    state: directory
    owner: root
    group: kvm
    mode: 0775

- name: Download Ubuntu cloud image
  get_url:
    url: https://cloud-images.ubuntu.com/releases/focal/release/ubuntu-20.04-server-cloudimg-amd64.img
    #checksum: sha256:https://cloud-images.ubuntu.com/releases/focal/release/SHA256SUMS
    #checksum: sha256:27cecebaf8c6334c56b66bf4759f9b001a35720323e1870a463a6f409229ff92
    checksum: sha256:e1264d4cca6c6c537e92f4e676cdc3cddbc5d7fe627d1d439d7e6973ebc2e216
    dest: /var/lib/libvirt/terraform/base_images/ubuntu-20.04-server-cloudimg-amd64.img
    owner: root
    group: kvm

- name: Download terraform binary
  get_url:
    url: https://releases.hashicorp.com/terraform/1.1.2/terraform_1.1.2_linux_amd64.zip
    #checksum: sha256:https://releases.hashicorp.com/terraform/1.1.2/terraform_1.1.2_SHA256SUMS
    checksum: sha256:734efa82e2d0d3df8f239ce17f7370dabd38e535d21e64d35c73e45f35dfa95c
    dest: /opt/bin/terraform_1.1.2_linux_amd64.zip
    owner: root
    group: root

- name: extract terraform zip file
  ansible.builtin.unarchive:
    src: /opt/bin/terraform_1.1.2_linux_amd64.zip
    dest: /opt/bin/
    owner: root
    group: root
    mode: 0755
