---
- name: Install needed packages for Ubuntu 20.04 to be a hypervisor
  apt:
    pkg: "{{ ubuntu_2004lts_pkgs }}"

- name: remove contents of /etc/netplan/
  shell: /bin/rm -rf /etc/netplan/*

- name: update netplan file
  ansible.builtin.template:
    src: templates/netplan_static-ip_bridge.yaml.j2
    dest: /etc/netplan/static-bridge.yaml
    owner: root
    group: root
    mode: '0644'

# https://github.com/dmacvicar/terraform-provider-libvirt/commit/22f096d9
- name: Disable SELinux enforcement in qemu.conf
  ansible.builtin.lineinfile:
    path: /etc/libvirt/qemu.conf
    regexp: '^security_driver = "none"$'
    insertafter: '^#security_driver = "selinux"$'
    line: security_driver = "none"

- name: restart libvirtd to ensure it does not self influct selinux
  ansible.builtin.systemd:
    name: libvirtd.service
    state: restarted
